### ISSUE TITLE
Lettie's feedback Aug 17

### ISSUE THREAD

**Issue by anhnt** [anhnt/Northern-Vision-Institute#1]
Hi Anh,

It’s looking good!

Just a few things:
- With the mobile version, could you please disable the header always staying on top? As it is taking up too much space. It looks good on desktop, no need to change this.
- With the grey “Book an eye test” form box, could you please put less line breaks in between the copy and fields - there is too much gap. Also please shorten the height of the Submit Button. See screenshot attached.
- When will you put the correct navigation menus?
- When will you put in the correct copy as per the copy decks? At the moment the homepage is showing dummy copy.

Many thanks
Lettie
![unnamed](https://cloud.githubusercontent.com/assets/735555/9300007/de283c8c-44eb-11e5-8c9e-ef20f4e09e0a.png)

**Comment by anhnt** [comment]
Remaining: When will you put the correct navigation menus?

**Comment by lettiem** [comment]
With the navigation menus, please follow the menu labelling and structure in the sitemap I gave you.
